[build]
  command = "npm run build" # Command to build the site
  publish = ".next" # Directory where Next.js outputs static files
  functions = "netlify/functions" # Directory for Netlify serverless functions

[functions]
  included_files = ["netlify/functions/data/rsvp.db"]


[[redirects]]
  from = "/api/*" # Redirect API requests to serverless functions
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
