[build]
  command = "npm run build" # Command to build the site
  publish = ".next" # Directory where Next.js outputs static files
  functions = "netlify/functions" # Directory for Netlify serverless functions

[functions]
  included_files = ["netlify/functions/data/rsvp.db"]
  external_node_modules = ["sqlite3", "@babylonjs/core", "@babylonjs/loaders"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*" # Redirect API requests to serverless functions
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
