[build]
  command = "npm run build" # Command to build the site
  publish = ".next" # Directory where Next.js outputs static files
  functions = "netlify/functions" # Directory for Netlify serverless functions

[[plugins]]
  package = "@netlify/plugin-nextjs"
  inputs = { disableNextImage = false }

[[redirects]]
  from = "/api/*" # Redirect API requests to serverless functions
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

